<h1><center>Introduction to Numpy </center></h1>


## What's Numpy

##### NumPy is the fundamental package for scientific computing in Python.It provides a high-performance multidimensional array object, and tools for working with these arrays,It's mostly written in C or fortran and it do a lot of parallisation in the backgroud to make run faster.It run in near-C speeds.

## Import the library

In [1]:
import numpy as np


## Create arrays (ndarrays) using Numpy Built In functions

In [2]:
a = np.array([1, 2, 3])   # Create a rank 1 array

##### Numpy arrays (ndarray) are different from python arrays, they have already their own data type called ndarray.

In [3]:
print(type(a)) 

<class 'numpy.ndarray'>


In [6]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)" <shape is tuple that contain the dimetion of the tensor>
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"
print(b)

(2, 3)
1 2 4
[[1 2 3]
 [4 5 6]]


## Datatypes

In [47]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         
x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         


int64
float64
int64


## Numpy built In functions that are similar to MATLAB and R

In [18]:
a = np.zeros((2,2))   # Create an array of all zeros
b = np.ones((1,2))    # Create an array of all ones
c = np.full((2,2), 7)  # Create a constant array
d = np.eye(2)  # identity matrix (like in MATLAB)          
e = np.random.random((2,2))  # Create an array filled with random values                 
print( '{0} : {1}'.format("A ",a))
print( '{0} : {1}'.format("B ",b))
print( '{0} : {1}'.format("C ",c))
print( '{0} : {1}'.format("D ",d))
print( '{0} : {1}'.format("E ",e))


A  : [[0. 0.]
 [0. 0.]]
B  : [[1. 1.]]
C  : [[7 7]
 [7 7]]
D  : [[1. 0.]
 [0. 1.]]
E  : [[0.66387851 0.21122328]
 [0.10506842 0.16243935]]


##### Generate arrays with steps

In [26]:
f=np.arange(10) # create an array of size 10 ,starting from 0 and 1 spaced integers 
g=np.arange(2, 10, dtype=float) # same as f but the datatype is explicitly set to float
h=np.arange(2, 3, 0.1) # array ,starting from 2 to 3 spaced by 0.1 (the step), the size of the array is calculated automatically
i=np.linspace(1., 4., 6,endpoint=False) # create to me an array  from 1.0 to 4.0 that contain exactly 6 elements  with same distance between each 2 
j=np.linspace(1., 4., 6,endpoint=True) # (Default) meaning that 4.0 should be included
print( '{0} : {1}'.format("F ",f))
print( '{0} : {1}'.format("G ",g))
print( '{0} : {1}'.format("H ",h))
print( '{0} : {1}'.format("I ",i))
print( '{0} : {1}'.format("J ",j))

F  : [0 1 2 3 4 5 6 7 8 9]
G  : [2. 3. 4. 5. 6. 7. 8. 9.]
H  : [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
I  : [1.  1.5 2.  2.5 3.  3.5]
J  : [1.  1.6 2.2 2.8 3.4 4. ]


You can read about other methods of array creation in the [documentation](https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation).

## Array indexing

### Slicing 

##### Template : a[ dimention1_start , dimention1_end : dimention2_start , dimention2_end : dimention3_start , dimention3_end...]

In [28]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # changing in B affect A !
print(a[0, 1])   # Prints "77"

2
77


##### Numpy offers several ways to index into arrays.

<h6> Two ways of accessing the data in the middle row of the array.<br>
 Mixing integer indexing with slices yields an array of lower rank,( if dimention 2 return dimention1)<br>
 while using only slices yields an array of the same rank as the original array ( if dimention 2 return dimention2)</h6>


In [35]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


##### Same apply for columns slicing

In [36]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  
print(col_r2, col_r2.shape)  

[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


### Integer array indexing:

##### Integer array indexing allows you to construct arbitrary arrays using the data from another array.

In [37]:
a = np.array([[1,2], [3, 4], [5, 6]])
# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

[1 4 5]


In [38]:
# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"


[1 4 5]


##### Boolean array indexing:

In [43]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2) # condition (return an array of boolean)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [46]:
print(a[bool_idx])  # it return 1D be carful

[3 4 5 6]


if you want to know more about boolean array indexing you should read the [documentation](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).


## Array math


In [49]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y) # sum of 2 matrices
print(np.add(x, y)) # same 

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [50]:
print(x - y)
print(np.subtract(x, y))


[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [53]:
print(x * y)
print(np.multiply(x, y)) # element by element multiplication
print(np.dot(x, y)) # matrix multiplication here 

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[19. 22.]
 [43. 50.]]


In [54]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"


10
[4 6]
[3 7]


In [55]:
##transpose a matrix
print(x.T)

[[1 3]
 [2 4]]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

### Broadcasting

In [57]:
# We will add the vector v to each row of the matrix x,
# using python loops etc is very slow, instead we let numpy do the job

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y) 


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### Numpy reshape

In [59]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


##### in case you don't know the resulting shape we can use the magic -1

In [62]:
print(x.reshape(-1))  # all in one dimention , guess how many elements are there 

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [63]:
x.reshape(-1,1) # all i know is one column ! guess the number of rows

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [64]:
x.reshape(-1, 2) # all i know is two columns ! guess the number of rows


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [65]:
x.reshape(1,-1) # all i know is one rows ! guess the number of cols

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [66]:
x.reshape(2, -1)  # all i know is two rows ! guess the number of cols


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [68]:
 x.reshape(-1, -1) # Error here , Numpy can only guess one dimenton :/

ValueError: can only specify one unknown dimension

In [ ]:
## exercice at then on creating and manipulating ndarrays !!!(to added below this)